# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Localmachine'

steps:
- script: |
    echo "Scheduling a delayed build..."
    az devops configure --defaults organization=https://dev.azure.com/saratraining97 project=trial project 
    sleep 60  # Delay for 1 minutes (60 seconds)
    az pipelines run --name "DelayedBuildPipeline" --branch $(Build.SourceBranchName)
  env:
    AZURE_DEVOPS_EXT_PAT: 3p5l2UJFV2kiULUbBk4qJXxhfyj7sIYnjDD0OpYDzdMudBPZZSnbJQQJ99ALACAAAAAAAAAAAAASAZDOULgg
  displayName: 'Schedule Delayed Build'


